server:
  port: 8080

spring:
  application:
    name: currency-exchange-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never